name: vmodel-control-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - casadi
  - cvxpy
  - numpy
  - osqp
  - pip
  - pytest
  - coverage
  - ruff
  - pre-commit
  - pip:
      - -e .
variables:
  PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
