"""Industrial-style signal logging and calibration utilities."""

from vcp.logging.calibration import (
    CalibrationBundle,
    CalibrationError,
    load_calibration,
    merge_calibration,
)
from vcp.logging.signal_dictionary import (
    DEFAULT_SIGNAL_DEFINITIONS,
    SignalDefinition,
    default_signal_dictionary,
    dump_signal_dictionary,
    load_signal_dictionary,
    required_signal_names,
    validate_required_signals,
)
from vcp.logging.signal_logger import (
    MF4ExportUnavailable,
    SignalLogArtifacts,
    SignalLogMetadata,
    SignalLogWriter,
    read_signal_log_csv,
    write_signal_log_csv,
)
from vcp.logging.virtual_can import (
    CONTROLLER_MODE_CODES,
    CONTROLLER_STATUS_MESSAGE_ID,
    FALLBACK_REASON_CODES,
    CANFrame,
    VirtualCANDependencyError,
    VirtualCANError,
    decode_controller_status_frame,
    encode_controller_status_frame,
    encode_controller_status_with_dbc,
    frame_to_python_can,
    load_dbc,
    rows_to_controller_status_frames,
    write_can_frames_jsonl,
)

__all__ = [
    "DEFAULT_SIGNAL_DEFINITIONS",
    "CalibrationBundle",
    "CalibrationError",
    "CANFrame",
    "CONTROLLER_MODE_CODES",
    "CONTROLLER_STATUS_MESSAGE_ID",
    "FALLBACK_REASON_CODES",
    "MF4ExportUnavailable",
    "SignalDefinition",
    "SignalLogArtifacts",
    "SignalLogMetadata",
    "SignalLogWriter",
    "VirtualCANDependencyError",
    "VirtualCANError",
    "decode_controller_status_frame",
    "default_signal_dictionary",
    "dump_signal_dictionary",
    "encode_controller_status_frame",
    "encode_controller_status_with_dbc",
    "frame_to_python_can",
    "load_calibration",
    "load_dbc",
    "load_signal_dictionary",
    "merge_calibration",
    "read_signal_log_csv",
    "required_signal_names",
    "rows_to_controller_status_frames",
    "validate_required_signals",
    "write_can_frames_jsonl",
    "write_signal_log_csv",
]
